#lang scheme

(require rnrs)
(require rnrs/mutable-pairs-6)

(define (make-queue)
  (let ((front-ptr '())
        (rear-ptr '()))
    (define (set-front-ptr! item)
      (set! front-ptr item))
    (define (set-rear-ptr! item)
      (set! rear-ptr item))
    (define (insert-queue! item)
      (let ((new-pair (cons item '())))
        (cond ((null? front-ptr)
               (set! front-ptr new-pair)
               (set! rear-ptr new-pair)
               (cons front-ptr rear-ptr))
              (else
               (set-cdr! rear-ptr new-pair)
               (set! rear-ptr new-pair)
               (cons front-ptr rear-ptr)))))
    (define (delete-queue!)
      (cond ((null? front-ptr)
             (error "DELETE! called with an empty queue" (cons front-ptr rear-ptr)))
            (else (set! front-ptr (cdr front-ptr))
                  (cons front-ptr rear-ptr))))
    (define (front-queue)
      (if (null? front-ptr)
          (error "FRONT called with an empty queue" (cons front-ptr rear-ptr))
          front-ptr))
 
    (define (dispatch m)
      (cond ((eq? m 'empty?)
             (null? front-ptr))
            ((eq? m 'insert)
             insert-queue!)
            ((eq? m 'delete)
             delete-queue!)
            ((eq? m 'front)
             front-queue)
            (else (error "Unknown operation" m))))
    dispatch))

(define (empty-queue? queue)
  (queue 'empty?))

(define (insert-queue! queue item)
  ((queue 'insert) item))

(define (delete-queue! queue)
  ((queue 'delete)))

(define (front-queue queue)
  ((queue 'front)))

(define (make-deque)
  (let ((front-ptr '())
        (rear-ptr '()))
    (define (set-front-ptr! item)
      (set! front-ptr item))
    (define (set-rear-ptr! item)
      (set! rear-ptr item))
    (define (front-insert-queue! item)
      (let ((new-pair (cons item '())))
        (cond ((null? front-ptr)
               (set! front-ptr new-pair)
               (set! rear-ptr new-pair)
               (cons front-ptr rear-ptr))
              (else
               (set! front-ptr (cons (car new-pair) front-ptr))
               (cons front-ptr rear-ptr)))))
    (define (rear-insert-queue! item)
      (let ((new-pair (cons item '())))
        (cond ((null? front-ptr)
               (set! front-ptr new-pair)
               (set! rear-ptr new-pair)
               (cons front-ptr rear-ptr))
              (else
               (set-cdr! rear-ptr new-pair)
               (set! rear-ptr new-pair)
               (cons front-ptr rear-ptr)))))
    ; не могу удалить. т.к. последний не знает про предыдущий. и не могу
    ; передвинуть на него указатель
    (define (rear-delete-queue!)
      (cond ((null? front-ptr)
             (error "DELETE! called with an empty deque" (cons front-ptr rear-ptr)))
            (else (set-cdr! front-ptr '())
                  (cons front-ptr rear-ptr))))

    (define (front-delete-queue!)
      (cond ((null? front-ptr)
             (error "DELETE! called with an empty deque" (cons front-ptr rear-ptr)))
            (else (set! front-ptr (cdr front-ptr))
                  (cons front-ptr rear-ptr))))
    (define (front-deque)
      (if (null? front-ptr)
          (error "FRONT called with an empty deque" (cons front-ptr rear-ptr))
          front-ptr))

    (define (rear-deque)
      (if (null? rear-ptr)
          (error "REAR called with an empty deque" (cons front-ptr rear-ptr))
          rear-ptr))
    
    (define (dispatch m)
      (cond ((eq? m 'empty?)
             (null? front-ptr))
            ((eq? m 'front-insert)
             front-insert-queue!)
            ((eq? m 'rear-insert)
             rear-insert-queue!)
            ((eq? m 'front-delete)
             front-delete-queue!)
            ((eq? m 'rear-delete)
             rear-delete-queue!)
            
            ((eq? m 'delete)
             delete-queue!)

            ((eq? m 'front)
             front-deque)
            ((eq? m 'rear)
             rear-deque)
            (else (error "Unknown operation" m))))
    dispatch))

(define (empty-deque? deque)
  (deque 'empty?))

(define (front-insert-queue! deque item)
  ((deque 'front-insert) item))

(define (rear-insert-queue! deque item)
  ((deque 'rear-insert) item))

(define (front-delete-queue! deque)
  ((deque 'front-delete)))

(define (rear-delete-queue! deque)
  ((deque 'rear-delete)))

(define (front-deque deque)
  ((deque 'front)))

(define (rear-deque deque)
  '()
  )


(define q1 (make-queue))
(define d1 (make-deque))

(empty-deque? d1)
(front-insert-queue! d1 'a)
(front-insert-queue! d1 'b)
(rear-insert-queue! d1 '-a)
(rear-insert-queue! d1 '-b)

